Use racks in ccg
qoollo/bob pull request #186
Opened 2021-03-04 20:27 UTC by vovac12

2021-04-03 11:08 UTC, idruzhitskiy requested changes
1. There should be Result+Error Message instead of None+Logs
2. There are hiddent mutability in center, rack etc methods (.inc()). It should be avoided, either by moving this counts to center (couple of Map<.., usize>), or marking those methods mutable. IMO first option is better and more maintainable

2021-04-03 11:08 UTC, idruzhitskiy commented on bob-tools/bin/config_cluster_generator/center.rs
> +                            .expect("no racks in setup")
You should make "new" method accept racks, and check there it's emptyness. This way you can omit "Option" in "next_" methods, as you'll be sure it's not empty

2021-04-03 11:08 UTC, idruzhitskiy commented on bob-tools/bin/config_cluster_generator/center.rs
> +                            .expect("no racks in setup")
And "new" should  return Result<..Center>, so you can log error

2021-04-17 16:12 UTC, idruzhitskiy commented on bob-tools/bin/config_cluster_generator/center.rs
> +    racks_used_count: HashMap<String, usize>,
IMO it's better to use type aliases here (like `type RackName = String`), it'll be more readable

2021-04-17 16:26 UTC, idruzhitskiy reviewed
Functions probably too large and should be split, otherwise LGTM

2021-04-17 17:41 UTC, agend commented
It just hit me that term rack is a bit weird,especially for cloud environments. Would it make sense to rename to availability group or something similar?

2021-04-19 15:12 UTC, pyakushin requested changes
Can you provide an example of cluster config with racks?

2021-04-19 21:45 UTC, vovac12 commented
> Can you provide an example of cluster config with racks?

Done

2021-07-27 10:25 UTC, pyakushin approved these changes
LGTM

2021-08-03 14:08 UTC, merged